baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'
publishDir = "docs"
baseURL = "https://davidlorenzana.github.io/flo/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.111.0"
