backend:
  name: github
  branch: main # o 'master' si es la rama principal de tu repositorio
  repo: davidlorenzana/flo # Reemplaza con tu usuario y nombre de repositorio

media_folder: "static/images" # Carpeta para subir imágenes
public_folder: "/images" # Carpeta pública para imágenes

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Cuerpo", name: "body", widget: "markdown"}
