backend:
  name: git-gateway
  branch: master # O master, dependiendo de tu rama principal

local_backend: true # Útil para pruebas en local

# Habilita el control de autenticación de Netlify Identity
publish_mode: editorial_workflow

# Define las colecciones de contenido (puedes añadir más)
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {label: 'Título', name: 'title', widget: 'string'}
      - {label: 'Fecha', name: 'date', widget: 'datetime'}
      - {label: 'Etiquetas', name: 'tags', widget: 'list', required: false}
      - {label: 'Cuerpo', name: 'body', widget: 'markdown'}
