site_url: https://davidlorenzana.github.io/flo/

# Backend para autenticación y almacenamiento de archivos
backend:
  name: github
  branch: master
  repo: davidlorenzana/flo
  base_url: https://sveltia-cms-auth.davlorenzana.workers.dev

# Opcional: Para probar en local con `npx netlify-cms-proxy-server`
# local_backend: true

# Habilita el control de autenticación de Netlify Identity y flujo editorial
auth_probe_url: https://api.netlify.com/auth # Asegúrate que esta URL esté presente
publish_mode: editorial_workflow

# Configuración para el manejo de archivos multimedia
media_folder: 'static/uploads' # Ruta relativa a la raíz del repositorio
public_folder: '/uploads'      # URL relativa a la raíz de tu sitio web publicado

# Define las colecciones de contenido
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {label: 'Título', name: 'title', widget: 'string'}
      - {label: 'Fecha', name: 'date', widget: 'datetime'}
      - {label: 'Imagen Principal', name: 'image', widget: 'image', required: false}
      - {label: 'Etiquetas', name: 'tags', widget: 'list', required: false}
      - {label: 'Cuerpo', name: 'body', widget: 'markdown'}
