# Backend para autenticación y almacenamiento de archivos
backend:
  name: git-gateway
  branch: master # Asegúrate de que esta sea la rama correcta (main o master)

# Configuración del flujo de trabajo (opcional, pero recomendable)
publish_mode: editorial_workflow

# Configuración para el manejo de archivos multimedia
# media_folder es la ruta donde se guardarán las imágenes
media_folder: 'static/uploads' # La ruta es relativa a la raíz del repositorio de Git
# public_folder es la URL desde donde se sirven las imágenes
public_folder: '/uploads' # La ruta es relativa a la raíz de tu sitio web publicado

# Colecciones de contenido
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {label: 'Título', name: 'title', widget: 'string'}
      - {label: 'Fecha', name: 'date', widget: 'datetime'}
      - {label: 'Imagen Principal', name: 'image', widget: 'image', required: false}
      - {label: 'Etiquetas', name: 'tags', widget: 'list', required: false}
      - {label: 'Cuerpo', name: 'body', widget: 'markdown'}
