name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - master # ¡CAMBIO IMPORTANTE AQUÍ! La rama donde Sveltia CMS hace los commits.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true # Si usas temas de Hugo como submódulos Git
          fetch-depth: 0   # Necesario si tu tema es un submódulo o necesitas el historial completo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest' # O una versión específica, ej: '0.127.0'

      - name: Build Hugo site
        run: hugo --minify --destination docs # ¡CAMBIO IMPORTANTE AQUÍ! La salida va a la carpeta 'docs'

      - name: Add .nojekyll file to docs folder
        run: touch docs/.nojekyll # Asegura que GitHub Pages no use Jekyll

      - name: Commit and Push to Master (docs folder)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Build and deploy Hugo site to docs folder"
          file_pattern: "docs/" # Solo commitea los cambios dentro de la carpeta 'docs'
          branch: master # ¡IMPORTANTE! El push se hace a la misma rama 'master'
          # token: ${{ secrets.GITHUB_TOKEN }} # No es necesario definirlo aquí, git-auto-commit-action lo usa por defecto
